/**
 * One dated entry in a student's notes log. `id` is stable for the life of the
 * entry so it can be edited or deleted; `date` is an ISO `YYYY-MM-DD` day.
 */
export type DatedNote = {
    id: number
    date: string
    text: string
}

export type Student = {
    id: number
    studentId: string
    firstName: string
    lastName: string
    dob: string
    subjects: string[]
    school: string
    year: string
    /** Blended 0–100 figure. With progressBySubject present, the API keeps
        this as the rounded average of its values (REQ-014). */
    progress: number
    /** Progress per studied subject (0–100). Optional — older records carry
        only the blended figure. */
    progressBySubject?: Record<string, number>
    mode: 'Online' | 'Face to Face' | 'Both'
    /** Agreed monthly tuition fee for this student, in GBP. */
    fees: number
    /** Legacy single free-text note. Superseded by {@link datedNotes} in the UI
        but kept on the record for older data; not shown on the profile. */
    notes: string
    /** The student's dated notes log, newest activity first is up to the view.
        Optional — absent on records created before the log existed. */
    datedNotes?: DatedNote[]
    parentName: string
    contactNumber: string
    address: string
    /** Archived students have finished tutoring: they leave the active roster
        for the teacher-only Alumni view but keep their history (REQ-013).
        Absent/false means active. */
    isArchived?: boolean
    /** ISO date the student was archived. */
    archivedOn?: string
    /** The teacher's closing note, kept through archive and restore. */
    archiveNotes?: string
}

/**
 * Whether a class is still on. Only two states: whether a class was *held* is
 * derived (Scheduled + date in the past), not a third state to tick after every
 * lesson — only the exception needs an action.
 */
export type SessionStatus = 'Scheduled' | 'Cancelled'

export type ScheduledSession = {
    id: number
    studentId: number
    studentName: string
    year: string
    subject: string
    date: string
    time: string
    /** Length of the class in minutes (30 / 60 / 90 / 120). */
    durationMinutes: number
    /** Links the rows of a group class; absent on a solo class. */
    groupId?: string
    notes: string
    status: SessionStatus
}

/** Classes that are still on. Cancelled ones stay visible, but never count. */
export const activeSessions = (sessions: ScheduledSession[]) =>
    sessions.filter((session) => session.status !== 'Cancelled')

export type PaymentStatus = 'Paid' | 'Partial' | 'Pending'

/**
 * A student's bill for one month.
 *
 * `amountDue` is derived by the API: the per-session fee times the classes that
 * actually took place that month. It grows as lessons are taught, and a month
 * with no classes yet owes nothing.
 */
export type PaymentRecord = {
    id: number
    studentId: number
    studentName: string
    month: string
    /** The student's agreed price for a single session. */
    feePerSession: number
    /** How many classes actually took place this month. */
    sessionsHeld: number
    /** `feePerSession × sessionsHeld`. */
    amountDue: number
    amountPaid: number
    outstanding: number
    status: PaymentStatus
    notes: string
}

/** Payment records for one month with server-computed totals (/payments/by-month). */
export type MonthlyPaymentGroup = {
    month: string
    totalDue: number
    totalReceived: number
    totalOutstanding: number
    /** Classes taught across every student this month. */
    sessionsHeld: number
    records: PaymentRecord[]
}

/**
 * Every student field the teacher can edit.
 *
 * `id` and `studentId` are omitted deliberately: `id` is the database key and
 * `studentId` is a generated human-facing code — both are identifiers, not
 * details, so they stay read-only.
 */
export type EditableStudentField = keyof Omit<Student, 'id' | 'studentId'>

/** The free-text fields, which all edit the same way. */
export const editableTextFields = [
    'firstName',
    'lastName',
    'school',
    'parentName',
    'contactNumber',
    'address',
    'notes',
] as const

export type StudentTextField = (typeof editableTextFields)[number]

/**
 * What the teacher records against a month.
 * Omit `amountPaid` to settle in full — the API pays exactly what the classes
 * came to, rather than a figure typed in the hope it matches.
 */
export type PaymentRecordInput = {
    studentId: number
    month: string
    amountPaid?: number
    notes?: string
}

// Student codes are generated by the API on create (studentService.upsertStudent),
// so the frontend never mints one.
