export type Student = {
    id: number
    studentId: string
    firstName: string
    lastName: string
    dob: string
    subjects: string[]
    school: string
    year: string
    progress: number
    mode: 'Online' | 'Face to Face'
    /** Agreed monthly tuition fee for this student, in GBP. */
    fees: number
    notes: string
    parentName: string
    contactNumber: string
    address: string
}

/**
 * Whether a class is still on. Only two states: whether a class was *held* is
 * derived (Scheduled + date in the past), not a third state to tick after every
 * lesson — only the exception needs an action.
 */
export type SessionStatus = 'Scheduled' | 'Cancelled'

export type ScheduledSession = {
    id: number
    studentId: number
    studentName: string
    year: string
    subject: string
    date: string
    time: string
    notes: string
    status: SessionStatus
}

/** Classes that are still on. Cancelled ones stay visible, but never count. */
export const activeSessions = (sessions: ScheduledSession[]) =>
    sessions.filter((session) => session.status !== 'Cancelled')

export type PaymentStatus = 'Paid' | 'Partial' | 'Pending'

export type PaymentRecord = {
    id: number
    studentId: number
    studentName: string
    month: string
    monthlyFee: number
    amountPaid: number
    status: PaymentStatus
    notes: string
}

/** Payment records for one month with server-computed totals (/payments/by-month). */
export type MonthlyPaymentGroup = {
    month: string
    totalExpected: number
    totalReceived: number
    totalOutstanding: number
    records: PaymentRecord[]
}

/**
 * Every student field the teacher can edit.
 *
 * `id` and `studentId` are omitted deliberately: `id` is the database key and
 * `studentId` is a generated human-facing code — both are identifiers, not
 * details, so they stay read-only.
 */
export type EditableStudentField = keyof Omit<Student, 'id' | 'studentId'>

/** The free-text fields, which all edit the same way. */
export const editableTextFields = [
    'firstName',
    'lastName',
    'school',
    'parentName',
    'contactNumber',
    'address',
    'notes',
] as const

export type StudentTextField = (typeof editableTextFields)[number]

/** Payload accepted by the updatePaymentRecord reducer. */
export type PaymentRecordInput = {
    studentId: number
    month: string
    status: PaymentStatus
    amountPaid: number
    notes: string
}

// Student codes are generated by the API on create (studentService.upsertStudent),
// so the frontend never mints one.
